// ─── Careers ──────────────────────────────────────────────────────────────────
export const careers = [
  { title: 'Senior Full-Stack Engineer', department: 'Engineering', location: 'Remote / Hyderabad', type: 'Full-Time', description: "You'll be building real products for real clients — not internal tools nobody uses. We work across a wide range of stacks, but React and Node.js are home base. If you care about code quality and enjoy seeing your work actually ship, you'll fit right in." },
  { title: 'AI/ML Engineer', department: 'AI', location: 'Remote', type: 'Full-Time', description: "We're looking for someone who can take an AI idea from 'interesting concept' to 'working in production'. You'll design and build LLM integrations, pipelines, and smart features — and be honest when something isn't the right tool for the job." },
  { title: 'Product Designer', department: 'Design', location: 'Remote / Hyderabad', type: 'Full-Time', description: "You'll own the end-to-end design of client products — from early wireframes to polished, production-ready UI. We care about design that works, not just design that looks good in a Dribbble post." },
  { title: 'DevOps Engineer', department: 'Infrastructure', location: 'Remote', type: 'Full-Time', description: "You'll be the reason things don't break at 2am. We run on AWS and GCP, with a strong CI/CD culture and a genuine belief that infrastructure should be boring in the best possible way." },
  { title: 'Mobile Engineer (React Native)', department: 'Engineering', location: 'Remote', type: 'Full-Time', description: "You know the difference between an app that feels native and one that just looks like it. You'll build polished iOS and Android apps for clients who care about the details as much as you do." },
  { title: 'Growth Engineer', department: 'Growth', location: 'Remote / Hyderabad', type: 'Full-Time', description: "Equal parts engineer and analyst. You'll build the systems that help us and our clients understand what's driving growth — and then act on it. You form hypotheses, run experiments, and let the data tell the story." },
]

// ─── FAQs ─────────────────────────────────────────────────────────────────────
export const faqs = [
  { question: 'What kinds of companies do you typically work with?', answer: "All sorts, honestly — from founders with a napkin sketch to engineering teams at established companies who need an extra gear. We do our best work with B2B SaaS, FinTech, HealthTech, and AI-first products, but if the problem is interesting, we're happy to talk." },
  { question: 'How long will my project actually take?', answer: "For a focused MVP: usually 8 to 12 weeks. For a full product launch: 12 to 20 weeks, depending on scope. We ship in weekly sprints so you're always seeing real progress — not waiting months for a big reveal." },
  { question: 'What happens after we launch?', answer: "Launching is just the beginning. We offer flexible ongoing arrangements — some clients keep us on a retainer for new features and improvements, others come back when they need to scale. Either way, we don't disappear after go-live." },
  { question: 'How does pricing work?', answer: "We do both fixed-price projects and dedicated team models. Which makes more sense depends on how well-defined your scope is and how fast things are likely to change. Book a call and we'll give you a straight answer." },
  { question: 'Can you actually help with AI, or is that just on the website?', answer: "It's genuinely what we spend a lot of time on. We've integrated GPT models, built RAG pipelines, trained custom classifiers, and designed AI workflows for clients across different industries. We're happy to be specific about what's possible for your use case." },
  { question: 'Do you work with clients outside India?', answer: "Yes — most of our clients are international, actually. We work across time zones and run async-friendly processes so nothing falls through the cracks. Regular video syncs keep everyone aligned." },
]

// ─── Process Steps ────────────────────────────────────────────────────────────
export const processSteps = [
  { step: 'Discovery',     detail: "We sit down and really dig into what you're trying to do — your goals, your constraints, who you're building for, and what success looks like. No templates, just honest conversation.", icon: '01', duration: '1 week' },
  { step: 'Architecture',  detail: "Before we write a line of code, we map out the right technical approach. Stack choices, infrastructure design, security considerations — the decisions that are much cheaper to make now than to change later.", icon: '02', duration: '1 week' },
  { step: 'Design Sprint', detail: "We talk to users, sketch out flows, build prototypes, and get them in front of real people. By the end, you have high-fidelity designs and a clear picture of exactly what we're building.", icon: '03', duration: '2 weeks' },
  { step: 'Development',   detail: "This is where we build. We work in tight sprints with daily standups and ship something every week. You see real progress constantly — no surprises, no black boxes.", icon: '04', duration: '6–12 weeks' },
  { step: 'Launch',        detail: "We handle the deployment, make sure everything is monitored, tune performance, and support your go-to-market push. Launch day is exciting — we make sure it stays that way.", icon: '05', duration: '1 week' },
  { step: 'Scale',         detail: "Once you're live, the real learning starts. We help you act on what users are telling you, keep the system healthy as you grow, and keep improving what matters.", icon: '06', duration: 'Ongoing' },
]

// ─── Project Images ─────────────────────────────────────────────────────────
import imgAmaravathi  from './assets/projects/amaravathi real estate.jpg'
import imgMatrimony   from './assets/projects/matrimony application.jpg'
import imgVasudha     from './assets/projects/vasudha reality.jpg'

// ─── Projects ─────────────────────────────────────────────────────────────────
export const projects = [
  { title: 'Amaravathi Real Estate', industry: 'Real Estate', description: 'A premium real estate platform for Amaravathi — the emerging capital region of Andhra Pradesh. Buyers, sellers, and agents all in one place, with smart property discovery and verified listings.', results: 'Thousands of verified listings. 60% faster property discovery. Trusted by buyers across Andhra Pradesh.', technologies: ['React', 'Node.js', 'PostgreSQL', 'Google Maps API', 'AWS'], image: imgAmaravathi },
  { title: 'Matrimony Application', industry: 'Social / Matrimony', description: 'A full-featured matrimony platform connecting families and individuals across communities. Smart matchmaking, horoscope compatibility, profile verification, and secure in-app messaging built for trust and privacy.', results: 'Thousands of successful matches. 4.8★ app rating. Active users across 10+ states in India.', technologies: ['Flutter', 'Java Spring Boot', 'PostgreSQL', 'Firebase', 'Razorpay', 'Redis'], image: imgMatrimony },
  { title: 'Vasudha Realty', industry: 'Real Estate', description: 'A modern real estate platform for Vasudha Realty — connecting buyers, sellers, and agents across premium residential and commercial properties. Smart search filters, virtual property tours, verified listings, and a seamless enquiry system built for serious buyers.', results: 'Hundreds of verified listings live at launch. 45% increase in qualified leads. Enquiry-to-site-visit conversion up 3x.', technologies: ['React', 'Node.js', 'PostgreSQL', 'Google Maps API', 'AWS', 'Razorpay'], image: imgVasudha },
  { title: 'Velocity Analytics Platform', industry: 'B2B SaaS', description: 'A team was spending 40+ hours a month pulling data together manually just to produce reports their executives needed every week. We fixed that.', results: '87% less time spent on reporting. Over 2.4 million data points processed every day. Now used by 50,000+ people.', technologies: ['React', 'Python', 'PostgreSQL', 'Redis', 'AWS'], image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80' },
  { title: 'Nexus Healthcare Portal', industry: 'HealthTech', description: 'Patients in rural areas were waiting two weeks to see a specialist. We helped build a telemedicine platform that put a doctor a few taps away.', results: 'Over 120,000 consultations completed. 95% patient satisfaction. Now available in 12 countries.', technologies: ['Next.js', 'Node.js', 'MongoDB', 'WebRTC', 'Stripe'], image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&q=80' },
  { title: 'Orbit E-commerce Engine', industry: 'E-commerce', description: "A fast-growing DTC brand was selling on three different channels but managing them like they were separate businesses. Inventory was a mess. We cleaned it up.", results: '$12M in sales in the first year. A 3.2% conversion rate. Nearly half of customers come back for more.', technologies: ['Next.js', 'Shopify', 'GraphQL', 'Algolia', 'Vercel'], image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80' },
  { title: 'ClearDesk', industry: 'AI/ML', description: 'A growing SaaS company was burying their support team under repetitive tickets. Same 12 questions, over and over, at all hours. We built an AI layer that understood their product well enough to handle the routine stuff — so their team could focus on the problems that actually needed a human.', results: '68% of tickets handled without human involvement. First response time cut from 19 hours to under 3 minutes. Support team headcount stayed flat while the user base doubled.', technologies: ['Python', 'OpenAI', 'LangChain', 'Pinecone', 'FastAPI'], image: 'https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=800&q=80' },
  { title: 'WealthLens', industry: 'FinTech', description: 'A boutique wealth management firm was running on spreadsheets and gut feel. Their advisors were spending more time chasing numbers than talking to clients. We built them a unified dashboard that pulled everything together — live portfolio data, tax exposure, client activity — in one place.', results: 'Advisors cut reporting time by 70%. Client review meetings went from quarterly to monthly. The firm onboarded 40 new HNI clients in the first 6 months after launch.', technologies: ['React', 'Django', 'PostgreSQL', 'Plaid', 'D3.js'], image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80' },
  { title: 'StockSense', industry: 'Logistics', description: 'A mid-size manufacturer kept running into the same two problems every quarter — either they ran out of stock and lost orders, or they over-ordered and tied up cash. Their forecasting was built on instinct and old Excel sheets. We replaced it with a system that actually learns.', results: 'Stockouts dropped by 62%. Excess inventory carrying costs down 38%. The ops team now gets weekly forecasts they actually trust — and act on.', technologies: ['Vue.js', 'Python', 'TensorFlow', 'IoT', 'Kafka'], image: 'https://images.unsplash.com/photo-1553413077-190dd305871c?w=800&q=80' },
]

// ─── Service Images ──────────────────────────────────────────────────────────
import imgWeb        from './assets/services/web developement card.jpg'
import imgMobile     from './assets/services/mobile app developement card.jpg'
import imgUI         from './assets/services/ui ux design.jpg'
import imgAI         from './assets/services/ai solutions.jpg'
import imgAutomation from './assets/services/automation systems.jpg'
import imgCloud      from './assets/services/cloud computing card.jpg'
import imgGrowth     from './assets/services/growth technology.jpg'
import imgBusiness    from './assets/services/Business Software.jpg'

export const SERVICE_IMAGES = {
  'Web Development':     imgWeb,
  'Mobile Applications': imgMobile,
  'UI/UX Design':        imgUI,
  'AI Solutions':        imgAI,
  'Automation Systems':  imgAutomation,
  'Cloud Solutions':     imgCloud,
  'Business Software':   imgBusiness,
  'Growth Technology':   imgGrowth,
}

// ─── Services ─────────────────────────────────────────────────────────────────
export const services = [
  { title: 'Web Development', description: "We build web products that are fast, solid, and actually enjoyable to use. Whether it's a marketing site, a SaaS dashboard, or a full platform — we make sure it loads quickly, scales without drama, and looks great doing it.", icon: <svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M3 9h18M9 21V9"/></svg>, benefits: ['Pages that load in under a second', 'SEO built in from the start', 'Scales as your user base grows'], stack: ['React', 'Next.js', 'Node.js', 'TypeScript', 'PostgreSQL'], outcome: 'Ship faster and spend less time fixing things that should just work.' },
  { title: 'Mobile Applications', description: "Your users are on their phones — we make sure your app feels right at home there. We build iOS and Android apps that are smooth, reliable, and the kind people actually keep installed.", icon: <svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><rect x="5" y="2" width="14" height="20" rx="2"/><line x1="12" y1="18" x2="12.01" y2="18"/></svg>, benefits: ['Feels native on every device', 'Works offline when needed', "Smart notifications that don't annoy people"], stack: ['React Native', 'Expo', 'Swift', 'Kotlin', 'Firebase'], outcome: 'An app your users love opening, not one they tolerate.' },
  { title: 'UI/UX Design', description: "Good design isn't decoration — it's the difference between a product people figure out in 30 seconds and one they abandon in frustration. We design things that are clear, beautiful, and built around how real people think.", icon: <svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><circle cx="12" cy="12" r="4"/><line x1="4.93" y1="4.93" x2="9.17" y2="9.17"/><line x1="14.83" y1="14.83" x2="19.07" y2="19.07"/><line x1="14.83" y1="9.17" x2="19.07" y2="4.93"/><line x1="4.93" y1="19.07" x2="9.17" y2="14.83"/></svg>, benefits: ['Design systems that grow with you', 'Flows that guide users naturally', 'Accessible to everyone'], stack: ['Figma', 'Framer', 'Principle', 'Lottie', 'Protopie'], outcome: 'Designs that convert visitors into happy, returning users.' },
  { title: 'AI Solutions', description: "AI is only useful if it actually solves something. We skip the hype and focus on integrations that save your team time, surface useful insights, and make your product smarter — without adding complexity.", icon: <svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M12 2a2 2 0 012 2c0 .74-.4 1.39-1 1.73V7h1a7 7 0 017 7h1a1 1 0 010 2h-1v1a7 7 0 01-7 7H9a7 7 0 01-7-7v-1H1a1 1 0 010-2h1a7 7 0 017-7h1V5.73A2 2 0 0110 4a2 2 0 012-2z"/><circle cx="9" cy="14" r="1"/><circle cx="15" cy="14" r="1"/></svg>, benefits: ['Workflows that run themselves', 'Insights that surface automatically', 'Automation that fits how you work'], stack: ['OpenAI', 'LangChain', 'Python', 'TensorFlow', 'Pinecone'], outcome: 'Less manual work, more time for the things that matter.' },
  { title: 'Automation Systems', description: "If someone on your team is doing the same thing every day, that's a job for software. We map out your repetitive processes and build systems that handle them automatically — so your people can focus on real work.", icon: <svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><polyline points="16 3 21 3 21 8"/><line x1="4" y1="20" x2="21" y2="3"/><polyline points="21 16 21 21 16 21"/><line x1="15" y1="15" x2="21" y2="21"/><line x1="4" y1="4" x2="9" y2="9"/></svg>, benefits: ['Processes that run without you', 'Fewer human errors', "Visibility into what's happening in real time"], stack: ['n8n', 'Zapier', 'AWS Lambda', 'Temporal', 'Kafka'], outcome: 'Give your team their time back — we handle the boring stuff.' },
  { title: 'Cloud Solutions', description: "Moving to the cloud, or already there but paying too much? We help you set things up properly — resilient, secure, and sized right for your actual usage. No over-engineering, no surprise bills.", icon: <svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M18 10h-1.26A8 8 0 109 20h9a5 5 0 000-10z"/></svg>, benefits: ['Stays up when things go wrong', 'Scales automatically with demand', 'Optimised costs from day one'], stack: ['AWS', 'GCP', 'Docker', 'Kubernetes', 'Terraform'], outcome: 'Infrastructure you can trust, at a price that makes sense.' },
  { title: 'Business Software', description: "Off-the-shelf tools often almost fit — but not quite. We build the internal tools, dashboards, and custom platforms that fit exactly how your business operates, not the other way around.", icon: <svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><rect x="2" y="3" width="20" height="14" rx="2"/><line x1="8" y1="21" x2="16" y2="21"/><line x1="12" y1="17" x2="12" y2="21"/></svg>, benefits: ['Built around your actual workflows', 'Real-time data where you need it', 'Connects with the tools you already use'], stack: ['React', 'GraphQL', 'PostgreSQL', 'Redis', 'Stripe'], outcome: 'Software that feels like it was made for you — because it was.' },
  { title: 'Growth Technology', description: "Growing a product is part craft, part science. We build the analytics, experiments, and systems that help you understand what's working, double down on it, and stop wasting budget on what isn't.", icon: <svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><line x1="18" y1="20" x2="18" y2="10"/><line x1="12" y1="20" x2="12" y2="4"/><line x1="6" y1="20" x2="6" y2="14"/><line x1="2" y1="20" x2="22" y2="20"/></svg>, benefits: ['Clear view of your growth funnel', 'A/B testing done properly', 'Retention systems that compound over time'], stack: ['Segment', 'Amplitude', 'Mixpanel', 'GTM', 'PostHog'], outcome: 'More signal, less guesswork — growth that keeps building on itself.' },
]

// ─── Team ─────────────────────────────────────────────────────────────────────
export const team = [
  { name: 'Alex Rivera',    role: 'Founder & CEO',            specialty: 'Product Strategy & Business Design',    bio: "Spent years at Google figuring out what makes products stick. Started TZMicha because he kept seeing great ideas fail due to poor execution. He's the one asking 'but why are we building this?'", avatar: 'AR' },
  { name: 'Priya Sharma',   role: 'Chief Technology Officer', specialty: 'Systems Architecture & Infrastructure',  bio: "Fifteen years making distributed systems behave. Previously at Netflix and Stripe. She has a gift for seeing the failure modes no one else spots — before they become production incidents.", avatar: 'PS' },
  { name: 'Jordan Kim',     role: 'Head of Design',           specialty: 'Product Design & Design Systems',       bio: "Led design at Airbnb and Figma. Jordan believes most interfaces make people feel dumb, and has spent a career fixing that. Four Webby Awards in the trophy case, zero ego about them.", avatar: 'JK' },
  { name: 'Marcus Chen',    role: 'Head of Engineering',      specialty: 'Full-Stack Engineering & DevOps',       bio: "Built and scaled engineering teams at Coinbase and Shopify. MIT CS graduate who still writes code every day. His rule: if it needs a manual to use, it needs more work.", avatar: 'MC' },
  { name: 'Sofia Martinez', role: 'AI/ML Lead',               specialty: 'Machine Learning & Data Science',       bio: "Stanford AI PhD and former OpenAI researcher. Sofia is the person who figures out where AI is actually useful — and firmly discourages the team from using it where it isn't.", avatar: 'SM' },
  { name: 'David Park',     role: 'Growth Engineer',          specialty: 'Growth Systems & Product Analytics',    bio: "Ran growth at Uber and DoorDash. David treats every assumption as a hypothesis to be tested. He's allergic to decisions made by gut feeling when the data is sitting right there.", avatar: 'DP' },
]

// ─── Testimonials ─────────────────────────────────────────────────────────────
export const testimonials = [
  { quote: "We went from 5,000 to 100,000 users in 10 weeks and nothing broke. I honestly didn't think that was possible until TZMicha made it happen. They think about the product, not just the code.", name: 'Sarah Chen',      role: 'Founder & CEO',        company: 'Vertex Analytics',   rating: 5, avatar: 'SC' },
  { quote: "It felt like working with a co-founder who actually understood the technical side. They pushed back when we were wrong, built fast when we were right, and delivered something we're genuinely proud of.", name: 'Marcus Johnson', role: 'CTO',                  company: 'Aurora Health',      rating: 5, avatar: 'MJ' },
  { quote: "The automation system they built saved us $600K in year one. But what I appreciated most was how carefully they thought through edge cases we hadn't even considered.", name: 'Elena Rodriguez', role: 'VP of Operations',     company: 'Nexus Supply',       rating: 5, avatar: 'ER' },
  { quote: "We handle 50 million API calls a day now with 99.99% uptime. That's not luck — that's architecture. TZMicha built something that actually holds up under pressure.", name: 'David Park',      role: 'Head of Engineering',  company: 'Prism Financial',    rating: 5, avatar: 'DP' },
  { quote: "Most dev shops build what you ask for and move on. TZMicha asks why you're asking for it. That shift in thinking is what got us to 3x ARR in 12 months.", name: 'Olivia Martinez', role: 'Chief Product Officer', company: 'Catalyst Commerce', rating: 5, avatar: 'OM' },
  { quote: "I've worked with a lot of development partners. TZMicha is the first one that felt like they were genuinely invested in the outcome, not just the delivery.", name: 'James Wu',         role: 'Founder',              company: 'Quantum Labs',       rating: 5, avatar: 'JW' },
]

// ─── Why Choose ───────────────────────────────────────────────────────────────
export const whyChoose = [
  { title: 'We think like founders',    description: "We care about whether the product succeeds, not just whether the code compiles. Every decision gets made with your business outcome in mind.", icon: <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20h9"/><path d="M16.5 3.5a2.121 2.121 0 013 3L7 19l-4 1 1-4L16.5 3.5z"/></svg> },
  { title: 'One team, the full stack',  description: "Design, engineering, infrastructure, AI — it's all under one roof. No handoff chaos, no finger-pointing between agencies. Just a team that owns the whole thing.", icon: <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="2" y="7" width="20" height="14" rx="2"/><path d="M16 7V5a2 2 0 00-2-2h-4a2 2 0 00-2 2v2"/></svg> },
  { title: 'We move fast — properly',   description: "Fast doesn't have to mean messy. We ship real, production-quality work every week, not rushed prototypes that need to be rebuilt in six months.", icon: <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/></svg> },
  { title: 'Built for the world',       description: "Whether your users are in Hyderabad or Houston, your product should work for them. We build with multi-region, multi-language, and global performance in mind from day one.", icon: <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><line x1="2" y1="12" x2="22" y2="12"/><path d="M12 2a15.3 15.3 0 014 10 15.3 15.3 0 01-4 10 15.3 15.3 0 01-4-10 15.3 15.3 0 014-10z"/></svg> },
  { title: 'AI where it actually helps', description: "We don't add AI to check a box. We look at your real workflows and figure out where intelligence genuinely reduces work or improves outcomes.", icon: <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 16V8a2 2 0 00-1-1.73l-7-4a2 2 0 00-2 0l-7 4A2 2 0 003 8v8a2 2 0 001 1.73l7 4a2 2 0 002 0l7-4A2 2 0 0021 16z"/></svg> },
  { title: 'No surprises, ever',         description: "You always know exactly where things stand. Daily updates, weekly demos, open communication. We think the worst thing a vendor can do is keep you guessing.", icon: <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M22 11.08V12a10 10 0 11-5.93-9.14"/><polyline points="22 4 12 14.01 9 11.01"/></svg> },
]
